name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python 3.14
        uses: actions/setup-python@v6
        with:
          python-version: 3.14
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pycodestyle pyright
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      # - name: Run tests with pytest
      #   run: |
      #     pytest
      - name: Lint with PyCodeStyle
        run: |
          find . -name \*.py -exec pycodestyle {} +
      - name: Type checking with PyRight
        run: |
          pyright
